import {
  mainnet,
  arbitrum,
  bsc,
  optimism,
  avalanche,
  arbitrumNova,
  arbitrumGoerli,
  avalancheFuji,
  base,
  blast,
  celo,
  goerli,
  hardhat,
  linea,
  merlin,
  okc,
  opBNB,
  polygon,
  polygonZkEvm,
  scroll,
  zksync,
  fantom,
} from 'viem/chains'

export enum ChainId {
  Mainnet = mainnet.id,
  Hardhat = hardhat.id,
  Arbitrum = arbitrum.id,
  Bsc = bsc.id,
  Optimism = optimism.id,
  Avalanche = avalanche.id,
  ArbitrumNova = arbitrumNova.id,
  ArbitrumGoerli = arbitrumGoerli.id,
  AvalancheFuji = avalancheFuji.id,
  Base = base.id,
  Blast = blast.id,
  Celo = celo.id,
  Goerli = goerli.id,
  Linea = linea.id,
  Merlin = merlin.id,
  Okc = okc.id,
  OpBNB = opBNB.id,
  Polygon = polygon.id,
  PolygonZkEvm = polygonZkEvm.id,
  Scroll = scroll.id,
  Zksync = zksync.id,
  Fantom = fantom.id,
}

export const SUPPORTED_CHAINS = [
  ChainId.Mainnet,
  ChainId.Hardhat,
  ChainId.Arbitrum,
  ChainId.Bsc,
  ChainId.Optimism,
  ChainId.Avalanche,
  ChainId.ArbitrumNova,
  ChainId.ArbitrumGoerli,
  ChainId.AvalancheFuji,
  ChainId.Base,
  ChainId.Blast,
  ChainId.Celo,
  ChainId.Goerli,
  ChainId.Linea,
  ChainId.Merlin,
  ChainId.Okc,
  ChainId.OpBNB,
  ChainId.Polygon,
  ChainId.PolygonZkEvm,
  ChainId.Scroll,
  ChainId.Zksync,
  ChainId.Fantom,
]

export const ChainConfigs = {
  [ChainId.Mainnet]: mainnet,
  [ChainId.Hardhat]: hardhat,
  [ChainId.Arbitrum]: arbitrum,
  [ChainId.Bsc]: bsc,
  [ChainId.Optimism]: optimism,
  [ChainId.Avalanche]: avalanche,
  [ChainId.ArbitrumNova]: arbitrumNova,
  [ChainId.ArbitrumGoerli]: arbitrumGoerli,
  [ChainId.AvalancheFuji]: avalancheFuji,
  [ChainId.Base]: base,
  [ChainId.Blast]: blast,
  [ChainId.Celo]: celo,
  [ChainId.Goerli]: goerli,
  [ChainId.Linea]: linea,
  [ChainId.Merlin]: merlin,
  [ChainId.Okc]: okc,
  [ChainId.OpBNB]: opBNB,
  [ChainId.Polygon]: polygon,
  [ChainId.PolygonZkEvm]: polygonZkEvm,
  [ChainId.Scroll]: scroll,
  [ChainId.Zksync]: zksync,
  [ChainId.Fantom]: fantom,
}
